# Numpy Array Operations:
Scenario: You are given a list of daily average temperatures (in degrees Celsius)
recorded over two weeks. Your task is to use NumPy to analyze this data.

1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
import numpy as np

In [ ]:
temparatures_w1=np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temparatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

2. Inspection and Properties:


● Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [ ]:
print(temparatures_w1.shape)
print(temparatures_w1.dtype)
print(temparatures_w1.size)

(7,)
float64
7

3. Array Operations:

● Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32

● Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
fahrenheit=temparatures_w1*(9/5)+32
print(fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [ ]:
print(temparatures_w1.max())
print(temparatures_w1.min())
print(temparatures_w1.mean())

26.1
20.8
23.542857142857144

4. Array Slicing and Indexing:

● Extract the temperatures for the first three days of the week.

● Extract the temperatures for the weekend (last two days).

● Extract the temperatures for the middle three days of the week.

In [ ]:
print(temparatures_w1[0:3])

[22.5 25.3 20.8]

In [ ]:
print(temparatures_w1[-2:])

[24.8 21.9]

In [ ]:
print(temparatures_w1[2:5])

[20.8 23.4 26.1]

5. Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [ ]:
temparatures=np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],
                      [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temparatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

6. Inspect and Slice the 2D Array:

● Inspect and print the shape, data type, and total number of elements in the
temperatures array.

● Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [ ]:
print(temparatures.shape)
print(temparatures.dtype)
print(temparatures.size)

(2, 7)
float64
14

In [ ]:
print(temparatures[0])

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [ ]:
print(temparatures[1])

[19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [ ]:
print(temparatures[:,-2:])

[[24.8 21.9]
 [22.8 20.1]]

# Explanation
1: First we have to import numpy so import numpy as np is uesd

2:created the array using the given data np.array code and find the shape using.shape,datatype by dtypes and no of elements by .size

3:for changing to fahrehheit we used a formula fahrenheit=temparatures_w1*(9/5)+32

For finding maximum temparature max() is used for minimum min() amd for calculating mean, mean() function is used

4:for first 3 days temparature we have to use [0:3] here 0 gives the first temparature and 3 indicates stop before 3d

for extacting weekend temparature that is the last 2 temparatures we have to use[-2:] here -2 means take 2 records from the last

for extacting middle 3 ,[2:5] is used means start from 2 and end before 5 .then we get the middle 3

5:np.array() is used to create 2d array and there must be 2 [] needed

6:For finding the shape, .shape and dtypes for datatype,.size for total elements

for extracting week1 temparature[0] and for week2 [1] is used and [:,-2:] is used for weekend values : means take all rows -2 means last 2 values

# Pandas Series:
1. Creating Pandas Series:

● Create a Pandas Series named marks with the following data:

➢ Marks: 95, 92, 89, 85, 80

➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [2]:
import pandas as pd

In [3]:
marks=pd.Series([95,92,89,85,80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

2. Indexing and Slicing:

● Use the integer index position to access the mark of the 1st rank student.

● Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.

● Use the iloc accessor to retrieve the mark of the 3rd rank student.

● Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [ ]:
print(marks.iloc[0])

95

In [ ]:
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
print(marks.iloc[2])

89

In [4]:
print(marks[marks>90])

Rank1    95
Rank2    92
dtype: int64

3. Manipulating Series:

● Modify the mark of the student with the 1st rank to 100.

● Remove the entry corresponding to the last rank from the Series.

● Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
marks.loc['Rank1']=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
marks=marks.drop('Rank5')
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
CGPA=marks/10
print(CGPA)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

# Explanation
First we have to import pandas so import pandas as pd is used

1: created the series(pd.Series()) using the given data with customised indexing and print used to display

2: for accessing the mark of 1st rank student iloc is used,it access values using their integer positions and [0] for 1st person

for retrieve the top 3 ranks loc function is used loc access the values by its index labels

for the mark of 3d rank student iloc[2] is used

for getting marks >90 we used print(marks[marks>90] is used

3: For changing the mark of first loc is used it select the value with label rank1 and assign 100

for removing rank5 value drop() is used

for calculating CGPA used the formula mark/10

# Pandas DataFrame:

1. Creating Pandas DataFrame:

● Create a Pandas DataFrame named transactions with the following data:

➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'

➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'

➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [ ]:
transactions=pd.DataFrame({ 'TransactionID':[ 101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                            'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics']
                            , 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
                            'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

In [ ]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

2. Data Exploration:

● Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.

In [ ]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
transactions.shape

(10, 4)

In [ ]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

● Display only the 'ProductCategory' and 'Amount' columns.

● Retrieve the last 3 columns of the DataFrame using iloc or loc.

● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

● Find the value counts for the 'ProductCategory' column.

● Find the unique values in the 'Region' column.

● Group by 'Region' and find the mean amount for each region.

In [ ]:
print(transactions[['ProductCategory','Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
print(transactions.iloc[:,-3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
print(transactions[(transactions['Region']=='North')&(transactions['Amount']>200)])

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']

In [ ]:
print(transactions.groupby('Region')['Amount'].mean())

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

# Explanation
1: For creating dataframe pd.DataFrame is used{} is used it hold the column names and values

2: for displaying the first 5 rows, head() is used and for last 5 rows tail() is used for no of rows and columns .shape is used for displaying column names only .columns is used and dtypes is used for datatype info() is used for getting complete information

For displaying 2 columns we put the 2 column names into [] and separated by comma

For retreiving last 3 columns iloc is used [:,-3:] : means select all rows -3 means select last 3 and iloc select using integer positons

For filtering we have to use & between the 2 conditions it check the region north and amount greater than 200

For finding value count .value_count() is used it counts how many times ecah values appears unique and print gives the result

For grouping region groupby() is used and for mean mean() is used it gives the mean of each region

3. Manipulating the DataFrame:

● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

● Add a new column 'Discount' by calculating 10% of the 'Amount'.

● Remove the row with TransactionID 109.

● Delete the 'Discount' column from the DataFrame.

In [ ]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
transactions['Discount']=transactions['Amount']*0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
transactions=transactions.drop(transactions[transactions['TransactionID']==109].index)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
transactions=transactions.drop(columns=['Discount'])
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

# Explanation

 For changing the amount of 102 ID first loc[] is used to select the amount value in matching row and assign the new value

 For calcutating discount with 10% we have to add a new column and using the formula amount/.10 to calculate the discount

 Next to remove a row with index 109 drop () is used first it check the value with ID 109 and .index return the value and drop() remove it

 For deleting the discount column .drop (columns) is used